export const games = [
  {
    id: 1,
    name: "Game 1",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Game 2",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Game 3",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "Game 4",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "Game 5",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    name: "Game 6",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    name: "Game 7",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    name: "Game 8",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    name: "Game 9",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    name: "Game 10",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 11,
    name: "Game 11",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 12,
    name: "Game 12",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 13,
    name: "Game 13",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 14,
    name: "Game 14",
    releaseDate: "2022-01-01",
    genres: ["Action", "Adventure"],
    rating: 4.5,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 15,
    name: "Game 15",
    releaseDate: "2023-03-15",
    genres: ["RPG", "Strategy"],
    rating: 4.0,
    image: "https://via.placeholder.com/150",
  },
];
